jobs:
  include:
  - stage: prepare
    language: java
    jdk: oraclejdk8
    before_install:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    script: mvn clean package
    after_success:
    - aws s3 cp ./target/aws-sns-webpush-1.0-SNAPSHOT.jar s3://travis-mtr/aws-sns-webpush/
  - stage: deploy
    language: node_js
    node_js: node
    before_install:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    - aws s3 sync s3://travis-mtr/aws-sns-webpush/ ./target
    - ls -la ./target
    - npm install serverless -g
    script: serverless deploy
env:
  global:
  - AWS_REGION: eu-central-1
  - secure: p4/rMx6r+wjJ3znAMfRtzcB/dYUWmNQgYAXX4co/zw4jM+DS5bPSx74GfzHLUEwBfbtIA+LHLlaEmYii0joZTQrAWA2uZ0saM24iQA1jfPeZuHDhgrJXnvL5ejnLjImCwwUYcu6KJM3lyjCBSUSzwgxJHXn2aDTuSEOC6gHwHGJUWx+FqQTHCbc+78bMKVbLYFk7yFern04hNnmr9rAUq2QxTvVrF5Rmrb9o7q8XRITTvOxGQIfthcAbPzIj5RVJc36aEDcYMK5j3yX1wzkAI9Up0Iyx5TFVt0DLcR1EcD5sUQF7o6P87SdQX3T0EfQ9L1qGgurYr+DTLEDGVjV3bexMv79WO64W8NTPu3BMG1Sypf9/OJwaXAP/10NXc0gD7uiiW9fGEPOsiieglC2vaElIlSBEDms4Nu/o3MIp6w3QXE2nRCDoEvFjEEV2598Fk0XDv63kduxsnTMswbxPV3v3TCU0xmVjVdq1nMi5gtuyYptQ+MXExzYFcglQS1s7Jjv8/StfJlJUgip9E74xkrgC2ZxdrDMxl/k/u0vWtAjMGck1+mMys9Qs4e4Ikw1Kx6CS9dKf4L+xeSd8ZWBSy2ySoIcwIX2UGl6jGd7j97mQ4dfyVqZ49nzMI6lG3g1VKJCBU7PJDPzTBDvzM6SPMYiqFB7+zJYZXa38TeavXVA=
  - secure: KGNBvz9Cubeb/rm9F6alLFqdZDgPSAIdeg9/0TYmIiIpyOQvBBtIIUuxxdH1+f/fEB2SzUiVkz2rMhyr6pjS2oQ1koc+2BBQzTILgQTNIJx+m3CVEEnGpElOYti/joewjxaKxD6k7rztXYL8Dhk4ASzxkOhhKBbPPZm8M+G+JpLhXuWBfNsaNvSDxSBNxw3qnpw3FVXNmzZiS17opD6XmIUdu3CePZg5syg2B66ERxYY8Tb2gZc/Kqg1i9GbMn6chh8WRQwGXnDfOc0388MAXAzyuEbTBsr+NaFSKb7Gat03qzvgeQyNmgC+DWgb9OUrp91d4T6GwwQVPdj5B1njOeKIB/KBEcmQt12E774t1K3qHc85Deu39Q6mPTia3Z0H9DAxvpHLMkxvzUa32V4dODOr2EKgIoA7GQmmIDwESJZXHv0ZNO54IBkdewGmMvfNv0eUq8oNpuMoQ/Szz4rjc73QRqYIEl94x7jThIig3oe7YiAARsgrI0Syzs4gjRyv3ZnMhGK8XgQqpIOoyyCheHYZTTy6asLcHNsXslH+2FFAecnafhEq4ENh8/1+yziBmtRPMG1orv6TvhimCkVOL06sypbHs7vEYwl9k39l7eSsdoOAWEf6/gV8GVZQcgpgG8biUGA5SEp0+mGX0b/Drdu9rukypat9db+HcNHZOcU=
  - secure: RADFA4pNkCeBcBnxLssCl419cfl32GzFxrkFDEC4ymILwwOz6xQ1U0+FjuFWrL9bsRMHdIyBDAy1BDuu6dleAXcDve9ZqWgIUc/K35bUhlkC31aej3xrwLsfZCpOLIb1FyrCkEF0F+jd1vxoY/12kgt9gScSo+1qaDFshwYc4GwsNYivOy2EwM6dx+YGfUygGVxKVG4cLGK9haQtxYas8FbAtqePwV8UfX1hL29y7NrQjv14V/HHbpTdI+G2cVfh6fjBRykJednvkry+xlY/e9BWi2HQ6gzIuBFwg4uKKoQODAifdU+r5JtLM4UB/jLqGhuefeiqODVjdayj+nTIPDzG3WRVKPMNRI8jMmDKxcTHOp62J2JlNxgCipyqrSMNIS65WkpA35OB5/XdLetpCBhz964qajhTO8pW48sXedhaf1FtlUa8lR+jzF98diFavd2Xclt75GRrOlD8lxMts/Lr4oH+uzXAqJIso7SYo6CzrgMN08BsiPtc0Nkc/K5xwbZ1YdMCAh+w3C3K9XDN/Mg2Vhq8nejPD2Lw22/yhdPsVsE1HJ/Ut3o3ut9phNZpFFxwnHH72eUdpfq3A2VLKrC+xg/Z7jK6br4ZVYAEUPbxugFg4r8Ma2mdRA6rVdndErfvShsWVZCerFjIFqOf/ewProgCuB8XxBtaszhVvMA=
  - secure: u8MGMzK/WIlbLPSSyRD/YAeYHf66VBiuAXlOfsODQGtSOLTN98J5MKoWhdN7JowyziyVoIYZzA/FUSn/vy6irLFNn0xFbRIytdZpTj71Yn+Sm9PdgWDbkNGGY1IWlIPU5wLJVBbqHjvAmPq8ULC096mkE4DMhwdNdtDgAP5ZZD4WbaB4b3yoIA4glvBDILpWGlqk9IcMHoAQpZrIcB34TNuW1YFyOmb67K3eUYjS+EzL5nzdj3TtPBFx/BMp8qNS1Txm0nUjUvfRAZDHmp5BFrkTg/Cgu1Wio9UCIG0oRgzE1PeajWFpmpRN610qaflUwXOAr9d4620mdgx836AFwDFX9hF1BOuI6YfoIkBdNgZiom/njI/P5CFMDtYf+xT26Fi00Nsr4qKKCKXIlnac9xz/L2dIvvwqKxEF4Yrf7KsDRzVn6WeSV6MEiio7PqOkyYzVV/2l5jqAwi2VcT+o77wNyZ3ZwpIVn0f/NIz513fK9cK0w1QFkaGVhIfkMaDGqnLpdBDOWWM3UNIiZ6Gtny80Vb1SFJDtsa7RSIh28l9LBWC4S6Q36dD7L+xV1nFYaapZ+VYy9/9Qq4aBqflhE4jOB96U6jWY+1p5mtr677WbQW9JjlxbbP1CHeXR8PRclTCc5a+wxhZXJ255pThbQtbzvvQNkoZ0bW8ywUfPZBE=
