jobs:
  include:
  - stage: prepare
    language: java
    jdk: oraclejdk8
    before_install:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    script: mvn clean package
    after_success:
    - aws s3 cp ./target/aws-sns-webpush-1.0-SNAPSHOT.jar s3://travis-mtr/aws-sns-webpush/
  - stage: deploy
    language: node_js
    node_js: node
    before_install:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    - aws s3 sync s3://travis-mtr/aws-sns-webpush/ ./target
    - ls -la ./target
    - npm install serverless -g
    script: serverless deploy
env:
  global:
  - AWS_REGION: eu-central-1
  - secure: swxHCFrBCQBqqA5K6v5pdOuOywhaM4x60JwpgfkNEeFiVSG/zX3oW+4w3IHax7yK9QPGSmSZJv7JZs6zcjecT1fqSoEEpberOLxiIUCd1yjIetLJpr4z9IxpmpTxwJd7Tdl3xV6dxH0EA17ejKLbaJZYczt66TBnQ9yrHJBEGfYMXgwn3w8AufVMZlcLFXFamh5tgZTUKX+mPxlmUeMX2dCeLb8Pr2KluhP5Xn93MTy0+B1dLoJ/nqS72T/j6q8ocjwIhEDYxjFDkzDSzJMQmFWT7iqN9juNHi9raXtxtV1GgRsvuxzo9XI7sBnrVDtoX/5xTs2q41B9OIMMK0yaZ4FqbB4SRO/uh3Nsp/mHFoF+Zq51AjQgaJUmDdbVJKSMuy7AUPWc59G1ygcIYD08L5VJzEw+u+M4Ij+Lz5qLxvL6leEWne1PpxNkWtleO3YbaFl0JacaHNkgOAUuNW1BPPVuFf6X7f3HFTTRJI0SBudSpk+3klCTiwUFsWaA9XfD3z4pQ/C7dJR5xGsq1GYE9C/ZePB7O7VLsYB9xN0nVnmXrJkbLQS2sPfC+RuyY1Np+izaUfcxYJOUaPpC16K+C2iMPfxokBS8VVMZcZT6RpdJxGkDkUdOY0Vz+WJnr/SnY3yebTQftBB5aP0Uph3YC0GxLGLhYTO7vlVeTabcx3I=
  - secure: g3loEpBk21+HantQVUr+064hi31w0gRMy3U6m8zWvnkxm45xa+KMM+RFXsSFLlPSadscfL2+hZFuCX/OHVrIkwFZDnigNtTrk7j/InYCpaf9zqCinmiBSmWZfmuSIa45+rmaZhC86U1/Imwnm1A/nnpvTkafiqscVDtINi+FmpJxDXqlzgZ9xbkP6k/5pN7rsg5btr6sGyjZW61e3x976SOw1dxFdcdir3pcdrf8EKsm2L8Btv8r5SqLndiN90xJuB4CbDjDEIZD4313UVJnsZPz9+O1d0MZXckVZrU6av19DSYKWlGSSW6c2WsBWxhtewFjziycZJdzVbs47dxq8Z+TiGG7yWzmLo8lSQaRZNRBsY2fxKlpv37dOpGrv3uE36iHdI1z57bpBQ72ZvwIbSCbjBth5A9WltCunX/GqRh/8jmGje/xgbgT8H34SRofR5erK4IjcDL3r81NghLXTiJ5S7a3HERHvRhaxQ2JIAqVJGrVQ5f0YONbspNjUt5oLDcrpOD/yMaBso+1L+IcoVWU0WkHHk3kWS4xShrrmhUm8dnVXooL6F4+KGhhzfcQWBPi+x76YChAZDCJVbW9ugPXvQV3lEOUd1RkRfs0G2BclWSEKmglDd7pNkAPT+effelITQ+tQl2mQgi09QTaSc4eTxZgtceIvIHtDgBuNrY=
  - secure: EdkLqgGxMpmD2Iq227+nwkrjNvr6+AoYdAnU28/hTCwOFJz21XuIKLcf/lp/pdv7ZeWxgdiu4gYwRv5yNK/Ca3fk/Y9TGAs2ouB7nKO0Jw1vziPzCC/6PANfWJmUp4YYxRKn//MYatj7ke/0z7nCwsv5/G8Roeq+B2ln1+UDCv8S7T0wKeOA61zVLKT57CjbJzcbM+1xDTkQ6l5u5oWpH6oSczh6wQKkKn0GSC0ZRZoFPbCaQkJKX4iC5k/2yjF0oQeI77aAogJK5DxpKL4tZCSE8fRdYOn/6EbK0ckQsgwp42gWL36KorBMe349qbBdoWmUT2DQP05+C2opuI1/LZ0KiygXbr5vzlaL9v2izBFiMu79HyLkQ3s5A4NSdl6PkM8umFaY/Rn0vyOyOQEni/0ouNQQPm0vGSoaQI8xcB2xmgGvpq5hbpCPVgmurpu2lYbl0xVOnSWYh6hh6xmHpikhVPWkI9huRtJVUi5FZps2z67LUcrArhBTRd5Akc/LT3nRmy04NZWrrhGmH/uORZ/WYzxNBN1O2j+flnOX9nUV3EIcNqxdG8/k+hjtfP0xzpcpQFss3xKjRJCoYJXKt9NW9BU4zLOQuTxrgRhFmTkqnbt1eX5ZUqTOIQ4Ehr16nhNKha47MGFVL7YvrNV9pOT8atYWDh/GkLS+r9TmPI0=
  - secure: Vk9vaNzgSRzNARtezw9ly4Ev56z51hmgndBRMEBEWwUq1wcQ0Y7hE8M6TZ11ewZfhmbUuV/OySzYPvE86tL4H6VvOB1y+LYjy94PUkzMZ15kAoK+kRGGUkNBmWf19f6GPVlbAUUp9lGCgV5136IlGfyRwbssgD+VaJ0uR99YP2UDpw+UIvcDVNAQaHYABSGX1O4acfe+PhDKF9W4ba/zicWnjFs+Vn14SYogWCBp/155WiUjrCAprqMUr2abL2qbxRwKYneL+jiJRWhoJoq21XMLKFkFHd2AmaE3wZz/KcC4Nf+sZG3zbuwNdvoz84FM6dohqKGZG70eDpg3Z7m52mxPR/KRWU3ZP07IRHMWc9Lpay40oZ3eJ9lcqV7UhTBn2dLBt/yZ6bqqm43fhEayVy4fQwwsHy/6iz+vpJJqb+ytpjPnxVkbuyNJayoirAXZNa6O3EpOf2IyCWaX/ZZNgK+q3T5OPGs12Yn2VcmzMUVPY2c1uegjSYW05O+SjzvxhYG/NiylHSStKHj3Hetrq9XakySYgaVIEAxoVPURkZX4kVrT48Dr9rRu4iSzMY9kVrEED836IKEEnLl3+OitkE9ecQMj2JXJgxHw4l/PyXm/CNSdp4UAMTY3noQ3vbfNfSQYc/uf+ayc8L56GX6t3qPrv3YuoRlzgQDFnY7N1SM=
